version: "3.8"
services:
  pantaloons1:
    image: abishnu08/pantaloons1:latest
    ports:
      - "1111:80"
    deploy:
      replicas: 3
  pantaloons2:
    image: abishnu08/pantaloons2:latest
    ports:
      - "2222:80"
    deploy:
      replicas: 3
  pantaloons3:
    image: abishnu08/pantaloons3:latest
    ports:
      - "3333:80"
    deploy:
      replicas: 3
